apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eiirdn48h-nodejs 
  janus-idp.io/tekton: eiirdn48h-nodejs
  backstage.io/kubernetes-id: eiirdn48h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eiirdn48h-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml