apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eiirdn48h-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: nexus-docker-nexus.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:eddf98bf4b511aee5401248e3bb02c629646e0ef@sha256:b987244c8a44b26ad209cde33b70ae3b6e9058173b6aa73d789cbcc1126109d9
          name: container-image
